### ISSUE TITLE
Assignment Week 3. 

### ISSUE THREAD

**Issue by shwaqas** [faizan170/piaic-batch4-faisalabad#2]
Hi,
Is there any `update` method for list exist? 
I can't find it 

**Update list using list update method:**

1. Change Name from 'Ali Raza' to 'Zohaib Ali'
2. Change No of subjects from 5 to 7

Please advise, should i skip it?

**Comment by zenoview** [comment]
[remove and insert.pdf](https://github.com/faizan170/piaic-batch4-faisalabad/files/4142195/remove.and.insert.pdf)

**Comment by faizan170** [comment]
listName[index] = NewValue
```python
data = ['Ali', 'Bilal', 'Nasir']
data[2] = ['Javaid']
```

**Comment by Ali-Raza378** [comment]
is it write to use del to remove value from list and then use insert function to give new value ????

['Ali Raza', 22, 91.24, 'Computer Science', 5, 'University of Agriculture']
del studentData[0]
studentData.insert(0,"Zohaib Ali")
print(studentData)
['Zohaib Ali', 22, 91.24, 'Computer Science', 5, 'University of Agriculture']

**Comment by ans92** [comment]
Where to upload the assignments?

**Comment by Mutahhar** [comment]
@Ali-Raza378 
> is it write to use del to remove value from list and then use insert function to give new value ????
> 
> ['Ali Raza', 22, 91.24, 'Computer Science', 5, 'University of Agriculture']
> del studentData[0]
> studentData.insert(0,"Zohaib Ali")
> print(studentData)
> ['Zohaib Ali', 22, 91.24, 'Computer Science', 5, 'University of Agriculture']

It will get the work done, but the better method is mentioned by Mr faizan as follows

> listName[index] = NewValue
> 
> ```python
> data = ['Ali', 'Bilal', 'Nasir']
> data[2] = ['Javaid']
> ```

This will update the value of list `data` at index `1` from `Bilal` to `Javaid`

**Comment by Ali-Raza378** [comment]
> @Ali-Raza378
> 
> > is it write to use del to remove value from list and then use insert function to give new value ????
> > ['Ali Raza', 22, 91.24, 'Computer Science', 5, 'University of Agriculture']
> > del studentData[0]
> > studentData.insert(0,"Zohaib Ali")
> > print(studentData)
> > ['Zohaib Ali', 22, 91.24, 'Computer Science', 5, 'University of Agriculture']
> 
> It will get the work done, but the better method is mentioned by Mr faizan as follows
> 
> > listName[index] = NewValue
> > ```python
> > data = ['Ali', 'Bilal', 'Nasir']
> > data[2] = ['Javaid']
> > ```
> 
> This will update the value of list `data` at index `1` from `Bilal` to `Javaid`

thanks sir.

**Comment by faizan170** [comment]
Closing issue now
